#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# sed: lit un fichier et applique les modifs. -i: modifie direct le fichier, pas de buffer
# On met la string que l'on veut supprimer dans le fichier et on la remplace avec echo
: > /etc/hosts
echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
